# Generated by Django 4.1.4 on 2022-12-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_after',
            field=models.FileField(upload_to='images/after'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_before',
            field=models.FileField(upload_to='images/before'),
        ),
    ]
